name: japanese_flashcard_application
description: "Japanese flashcard project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.0.0+3
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flip_card: ^0.7.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  kana_kit: ^2.1.1
  flutter_tts: ^3.6.3
  just_audio: ^0.9.46
  just_audio_libwinmedia: ^0.0.4+1
  flutter_slidable: ^3.1.2
  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - .env
